site_name: GEM CSC Bending Analyzer
repo_name: GitHub
repo_url: https://github.com/akhter-towsifa/GEMCSCBendingAnalyzer
theme:
  name: material
  font: false
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to system mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode (night time!)
  logo: https://cms.cern/sites/default/files/logo/cms_logo_neg03_2.png

nav:
  - Home: index.md
  - Quick Start: README.md
  - Detailed Instructions:
      - Configuration: configuration.md
      - Running the Analyzer: running.md
  - Understanding the GEM Alignment code: GEMAl.md
  - Understanding GEM CSC Bending Angle: bending.md
  